# Apriori

## Importing the libraries

In [28]:
!pip install apyori

Requirement already satisfied: apyori in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (1.1.2)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [17]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Data Preprocessing

In [18]:
dataset = pd.read_csv('Market_Basket_Optimisation.csv', header = None)
transactions = []
for i in range (0,750):
    transactions.append([str( dataset.values[i,j]) for j in range(0,20)])

## Training the Apriori model on the dataset

In [23]:
from apyori import apriori
rules = apriori(transactions = transactions,min_support=0.003,min_confidence =0.2,min_lift = 3,min_length = 2,max_length  = 2)

## Visualising the results

### Displaying the first results coming directly from the output of the apriori function

In [24]:
results = list(rules)
results

[RelationRecord(items=frozenset({'almonds', 'burgers'}), support=0.008, ordered_statistics=[OrderedStatistic(items_base=frozenset({'almonds'}), items_add=frozenset({'burgers'}), confidence=0.2857142857142857, lift=3.571428571428571)]),
 RelationRecord(items=frozenset({'almonds', 'soup'}), support=0.009333333333333334, ordered_statistics=[OrderedStatistic(items_base=frozenset({'almonds'}), items_add=frozenset({'soup'}), confidence=0.33333333333333337, lift=4.166666666666667)]),
 RelationRecord(items=frozenset({'milk', 'asparagus'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'asparagus'}), items_add=frozenset({'milk'}), confidence=0.6, lift=4.838709677419355)]),
 RelationRecord(items=frozenset({'avocado', 'soup'}), support=0.008, ordered_statistics=[OrderedStatistic(items_base=frozenset({'avocado'}), items_add=frozenset({'soup'}), confidence=0.27272727272727276, lift=3.4090909090909096)]),
 RelationRecord(items=frozenset({'milk', 'barbecue sauce'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'barbecue sauce'}), items_add=frozenset({'milk'}), confidence=0.42857142857142855, lift=3.456221198156682)]),
 RelationRecord(items=frozenset({'soup', 'barbecue sauce'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'barbecue sauce'}), items_add=frozenset({'soup'}), confidence=0.42857142857142855, lift=5.357142857142857)]),
 RelationRecord(items=frozenset({'ground beef', 'black tea'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'black tea'}), items_add=frozenset({'ground beef'}), confidence=0.375, lift=3.700657894736842)]),
 RelationRecord(items=frozenset({'black tea', 'herb & pepper'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'black tea'}), items_add=frozenset({'herb & pepper'}), confidence=0.375, lift=4.934210526315789)]),
 RelationRecord(items=frozenset({'black tea', 'milk'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'black tea'}), items_add=frozenset({'milk'}), confidence=0.375, lift=3.024193548387097)]),
 RelationRecord(items=frozenset({'black tea', 'salmon'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'black tea'}), items_add=frozenset({'salmon'}), confidence=0.375, lift=8.035714285714285)]),
 RelationRecord(items=frozenset({'black tea', 'spaghetti'}), support=0.006666666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'black tea'}), items_add=frozenset({'spaghetti'}), confidence=0.6250000000000001, lift=3.4722222222222228)]),
 RelationRecord(items=frozenset({'blueberries', 'cooking oil'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'blueberries'}), items_add=frozenset({'cooking oil'}), confidence=0.5, lift=9.375)]),
 RelationRecord(items=frozenset({'blueberries', 'soup'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'blueberries'}), items_add=frozenset({'soup'}), confidence=0.5, lift=6.25)]),
 RelationRecord(items=frozenset({'body spray', 'green tea'}), support=0.005333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'body spray'}), items_add=frozenset({'green tea'}), confidence=0.4444444444444444, lift=3.472222222222222)]),
 RelationRecord(items=frozenset({'body spray', 'soup'}), support=0.005333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'body spray'}), items_add=frozenset({'soup'}), confidence=0.4444444444444444, lift=5.555555555555555)]),
 RelationRecord(items=frozenset({'brownies', 'energy bar'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'brownies'}), items_add=frozenset({'energy bar'}), confidence=0.25, lift=6.46551724137931)]),
 RelationRecord(items=frozenset({'olive oil', 'brownies'}), support=0.005333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'brownies'}), items_add=frozenset({'olive oil'}), confidence=0.3333333333333333, lift=4.716981132075471)]),
 RelationRecord(items=frozenset({'gums', 'burgers'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'gums'}), items_add=frozenset({'burgers'}), confidence=0.3, lift=3.75)]),
 RelationRecord(items=frozenset({'butter', 'cottage cheese'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cottage cheese'}), items_add=frozenset({'butter'}), confidence=0.21428571428571427, lift=8.458646616541353)]),
 RelationRecord(items=frozenset({'cake', 'fresh tuna'}), support=0.005333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fresh tuna'}), items_add=frozenset({'cake'}), confidence=0.2222222222222222, lift=3.0864197530864197)]),
 RelationRecord(items=frozenset({'cake', 'toothpaste'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'toothpaste'}), items_add=frozenset({'cake'}), confidence=0.42857142857142855, lift=5.9523809523809526)]),
 RelationRecord(items=frozenset({'ground beef', 'carrots'}), support=0.005333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'carrots'}), items_add=frozenset({'ground beef'}), confidence=0.5, lift=4.934210526315789)]),
 RelationRecord(items=frozenset({'cereals', 'green tea'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cereals'}), items_add=frozenset({'green tea'}), confidence=0.42857142857142855, lift=3.3482142857142856)]),
 RelationRecord(items=frozenset({'chicken', 'extra dark chocolate'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'extra dark chocolate'}), items_add=frozenset({'chicken'}), confidence=0.5, lift=8.152173913043478)]),
 RelationRecord(items=frozenset({'fresh tuna', 'chicken'}), support=0.005333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fresh tuna'}), items_add=frozenset({'chicken'}), confidence=0.2222222222222222, lift=3.6231884057971016)]),
 RelationRecord(items=frozenset({'light cream', 'chicken'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'chicken'}), confidence=0.25, lift=4.076086956521739)]),
 RelationRecord(items=frozenset({'spaghetti', 'chutney'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chutney'}), items_add=frozenset({'spaghetti'}), confidence=0.75, lift=4.166666666666667)]),
 RelationRecord(items=frozenset({'cider', 'frozen vegetables'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cider'}), items_add=frozenset({'frozen vegetables'}), confidence=0.375, lift=4.136029411764706)]),
 RelationRecord(items=frozenset({'gums', 'cooking oil'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'gums'}), items_add=frozenset({'cooking oil'}), confidence=0.3, lift=5.624999999999999)]),
 RelationRecord(items=frozenset({'cooking oil', 'oil'}), support=0.006666666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'oil'}), items_add=frozenset({'cooking oil'}), confidence=0.29411764705882354, lift=5.514705882352941)]),
 RelationRecord(items=frozenset({'parmesan cheese', 'cooking oil'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'parmesan cheese'}), items_add=frozenset({'cooking oil'}), confidence=0.21428571428571427, lift=4.017857142857142)]),
 RelationRecord(items=frozenset({'frozen smoothie', 'cottage cheese'}), support=0.006666666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cottage cheese'}), items_add=frozenset({'frozen smoothie'}), confidence=0.35714285714285715, lift=6.868131868131869)]),
 RelationRecord(items=frozenset({'mushroom cream sauce', 'escalope'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.27272727272727276, lift=3.4668721109399083)]),
 RelationRecord(items=frozenset({'shallot', 'escalope'}), support=0.005333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'shallot'}), items_add=frozenset({'escalope'}), confidence=0.39999999999999997, lift=5.084745762711864)]),
 RelationRecord(items=frozenset({'frozen vegetables', 'extra dark chocolate'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'extra dark chocolate'}), items_add=frozenset({'frozen vegetables'}), confidence=0.5, lift=5.514705882352941)]),
 RelationRecord(items=frozenset({'turkey', 'extra dark chocolate'}), support=0.005333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'extra dark chocolate'}), items_add=frozenset({'turkey'}), confidence=0.6666666666666666, lift=8.474576271186441)]),
 RelationRecord(items=frozenset({'french fries', 'strawberries'}), support=0.008, ordered_statistics=[OrderedStatistic(items_base=frozenset({'strawberries'}), items_add=frozenset({'french fries'}), confidence=0.5, lift=3.125)]),
 RelationRecord(items=frozenset({'french wine', 'fresh bread'}), support=0.005333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'french wine'}), items_add=frozenset({'fresh bread'}), confidence=0.2222222222222222, lift=5.555555555555555)]),
 RelationRecord(items=frozenset({'french wine', 'frozen vegetables'}), support=0.008, ordered_statistics=[OrderedStatistic(items_base=frozenset({'french wine'}), items_add=frozenset({'frozen vegetables'}), confidence=0.3333333333333333, lift=3.6764705882352935)]),
 RelationRecord(items=frozenset({'olive oil', 'french wine'}), support=0.005333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'french wine'}), items_add=frozenset({'olive oil'}), confidence=0.2222222222222222, lift=3.144654088050314)]),
 RelationRecord(items=frozenset({'french wine', 'rice'}), support=0.005333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'french wine'}), items_add=frozenset({'rice'}), confidence=0.2222222222222222, lift=11.904761904761903), OrderedStatistic(items_base=frozenset({'rice'}), items_add=frozenset({'french wine'}), confidence=0.2857142857142857, lift=11.904761904761903)]),
 RelationRecord(items=frozenset({'rice', 'fresh bread'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'rice'}), items_add=frozenset({'fresh bread'}), confidence=0.21428571428571427, lift=5.357142857142857)]),
 RelationRecord(items=frozenset({'tomato juice', 'fresh bread'}), support=0.008, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fresh bread'}), items_add=frozenset({'tomato juice'}), confidence=0.2, lift=4.285714285714286)]),
 RelationRecord(items=frozenset({'honey', 'fresh tuna'}), support=0.005333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fresh tuna'}), items_add=frozenset({'honey'}), confidence=0.2222222222222222, lift=7.246376811594203)]),
 RelationRecord(items=frozenset({'fresh tuna', 'olive oil'}), support=0.009333333333333334, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fresh tuna'}), items_add=frozenset({'olive oil'}), confidence=0.3888888888888889, lift=5.50314465408805)]),
 RelationRecord(items=frozenset({'green grapes', 'frozen smoothie'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'green grapes'}), items_add=frozenset({'frozen smoothie'}), confidence=0.3, lift=5.769230769230769)]),
 RelationRecord(items=frozenset({'vegetables mix', 'frozen smoothie'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'vegetables mix'}), items_add=frozenset({'frozen smoothie'}), confidence=0.25, lift=4.8076923076923075)]),
 RelationRecord(items=frozenset({'gums', 'frozen vegetables'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'gums'}), items_add=frozenset({'frozen vegetables'}), confidence=0.3, lift=3.3088235294117645)]),
 RelationRecord(items=frozenset({'frozen vegetables', 'light mayo'}), support=0.006666666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light mayo'}), items_add=frozenset({'frozen vegetables'}), confidence=0.29411764705882354, lift=3.2439446366782008)]),
 RelationRecord(items=frozenset({'magazines', 'frozen vegetables'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'magazines'}), items_add=frozenset({'frozen vegetables'}), confidence=0.375, lift=4.136029411764706)]),
 RelationRecord(items=frozenset({'frozen vegetables', 'mashed potato'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mashed potato'}), items_add=frozenset({'frozen vegetables'}), confidence=0.6, lift=6.617647058823529)]),
 RelationRecord(items=frozenset({'tomato sauce', 'frozen vegetables'}), support=0.005333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'frozen vegetables'}), confidence=0.2857142857142857, lift=3.15126050420168)]),
 RelationRecord(items=frozenset({'green tea', 'toothpaste'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'toothpaste'}), items_add=frozenset({'green tea'}), confidence=0.42857142857142855, lift=3.3482142857142856)]),
 RelationRecord(items=frozenset({'ground beef', 'nonfat milk'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'nonfat milk'}), items_add=frozenset({'ground beef'}), confidence=0.5, lift=4.934210526315789)]),
 RelationRecord(items=frozenset({'gums', 'low fat yogurt'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'gums'}), items_add=frozenset({'low fat yogurt'}), confidence=0.3, lift=3.571428571428571)]),
 RelationRecord(items=frozenset({'gums', 'soup'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'gums'}), items_add=frozenset({'soup'}), confidence=0.3, lift=3.75)]),
 RelationRecord(items=frozenset({'mint', 'ham'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mint'}), items_add=frozenset({'ham'}), confidence=0.27272727272727276, lift=10.227272727272728)]),
 RelationRecord(items=frozenset({'pancakes', 'ham'}), support=0.006666666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'ham'}), items_add=frozenset({'pancakes'}), confidence=0.25, lift=3.676470588235294)]),
 RelationRecord(items=frozenset({'spaghetti', 'ham'}), support=0.014666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'ham'}), items_add=frozenset({'spaghetti'}), confidence=0.5499999999999999, lift=3.0555555555555554)]),
 RelationRecord(items=frozenset({'herb & pepper', 'light cream'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'herb & pepper'}), confidence=0.25, lift=3.2894736842105265)]),
 RelationRecord(items=frozenset({'herb & pepper', 'mint'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mint'}), items_add=frozenset({'herb & pepper'}), confidence=0.27272727272727276, lift=3.588516746411484)]),
 RelationRecord(items=frozenset({'herb & pepper', 'tomato sauce'}), support=0.006666666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'herb & pepper'}), confidence=0.35714285714285715, lift=4.699248120300752)]),
 RelationRecord(items=frozenset({'herb & pepper', 'whole wheat pasta'}), support=0.009333333333333334, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole wheat pasta'}), items_add=frozenset({'herb & pepper'}), confidence=0.2413793103448276, lift=3.1760435571687844)]),
 RelationRecord(items=frozenset({'light cream', 'olive oil'}), support=0.006666666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'olive oil'}), confidence=0.4166666666666667, lift=5.89622641509434)]),
 RelationRecord(items=frozenset({'light cream', 'soup'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'soup'}), confidence=0.25, lift=3.125)]),
 RelationRecord(items=frozenset({'light cream', 'tomato sauce'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'tomato sauce'}), confidence=0.25, lift=13.392857142857142), OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'light cream'}), confidence=0.21428571428571427, lift=13.392857142857142)]),
 RelationRecord(items=frozenset({'low fat yogurt', 'mushroom cream sauce'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'low fat yogurt'}), confidence=0.27272727272727276, lift=3.246753246753247)]),
 RelationRecord(items=frozenset({'low fat yogurt', 'oil'}), support=0.008, ordered_statistics=[OrderedStatistic(items_base=frozenset({'oil'}), items_add=frozenset({'low fat yogurt'}), confidence=0.3529411764705882, lift=4.201680672268907)]),
 RelationRecord(items=frozenset({'magazines', 'salmon'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'magazines'}), items_add=frozenset({'salmon'}), confidence=0.375, lift=8.035714285714285)]),
 RelationRecord(items=frozenset({'meatballs', 'soup'}), support=0.006666666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'meatballs'}), items_add=frozenset({'soup'}), confidence=0.2777777777777778, lift=3.4722222222222223)]),
 RelationRecord(items=frozenset({'spinach', 'mineral water'}), support=0.006666666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'spinach'}), items_add=frozenset({'mineral water'}), confidence=0.8333333333333334, lift=3.1887755102040822)]),
 RelationRecord(items=frozenset({'spaghetti', 'mint green tea'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mint green tea'}), items_add=frozenset({'spaghetti'}), confidence=0.75, lift=4.166666666666667)]),
 RelationRecord(items=frozenset({'shrimp', 'oil'}), support=0.005333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'oil'}), items_add=frozenset({'shrimp'}), confidence=0.2352941176470588, lift=3.0425963488843806)]),
 RelationRecord(items=frozenset({'tomato juice', 'oil'}), support=0.006666666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'oil'}), items_add=frozenset({'tomato juice'}), confidence=0.29411764705882354, lift=6.302521008403361)]),
 RelationRecord(items=frozenset({'olive oil', 'tomato sauce'}), support=0.005333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'olive oil'}), confidence=0.2857142857142857, lift=4.0431266846361185)]),
 RelationRecord(items=frozenset({'whole wheat pasta', 'olive oil'}), support=0.014666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'olive oil'}), items_add=frozenset({'whole wheat pasta'}), confidence=0.20754716981132074, lift=5.367599219258294), OrderedStatistic(items_base=frozenset({'whole wheat pasta'}), items_add=frozenset({'olive oil'}), confidence=0.3793103448275862, lift=5.367599219258295)]),
 RelationRecord(items=frozenset({'tea', 'pancakes'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tea'}), items_add=frozenset({'pancakes'}), confidence=0.75, lift=11.029411764705882)]),
 RelationRecord(items=frozenset({'pasta', 'shrimp'}), support=0.02666666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'shrimp'}), confidence=0.8695652173913044, lift=11.244377811094454), OrderedStatistic(items_base=frozenset({'shrimp'}), items_add=frozenset({'pasta'}), confidence=0.3448275862068966, lift=11.244377811094454)]),
 RelationRecord(items=frozenset({'salmon', 'yams'}), support=0.006666666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'yams'}), items_add=frozenset({'salmon'}), confidence=0.2, lift=4.285714285714286)]),

### Putting the results well organised into a Pandas DataFrame

In [25]:
def inspect(results):
    lhs         = [tuple(result[2][0][0])[0] for result in results]
    rhs         = [tuple(result[2][0][1])[0] for result in results]
    supports    = [result[1] for result in results]
    confidences = [result[2][0][2] for result in results]
    lifts       = [result[2][0][3] for result in results]
    return list(zip(lhs, rhs, supports, confidences, lifts))
resultsinDataFrame = pd.DataFrame(inspect(results), columns = ['Left Hand Side', 'Right Hand Side', 'Support', 'Confidence', 'Lift'])

### Displaying the results non sorted

In [26]:
resultsinDataFrame

    Left Hand Side    Right Hand Side   Support  Confidence       Lift
0          almonds            burgers  0.008000    0.285714   3.571429
1          almonds               soup  0.009333    0.333333   4.166667
2        asparagus               milk  0.004000    0.600000   4.838710
3          avocado               soup  0.008000    0.272727   3.409091
4   barbecue sauce               milk  0.004000    0.428571   3.456221
..             ...                ...       ...         ...        ...
75       olive oil  whole wheat pasta  0.014667    0.207547   5.367599
76             tea           pancakes  0.004000    0.750000  11.029412
77           pasta             shrimp  0.026667    0.869565  11.244378
78            yams             salmon  0.006667    0.200000   4.285714
79            soda               soup  0.004000    0.750000   9.375000

[80 rows x 5 columns]

### Displaying the results sorted by descending lifts

In [27]:
resultsinDataFrame.nlargest(n  = 10,columns='Lift')

          Left Hand Side Right Hand Side   Support  Confidence       Lift
65           light cream    tomato sauce  0.004000    0.250000  13.392857
40           french wine            rice  0.005333    0.222222  11.904762
77                 pasta          shrimp  0.026667    0.869565  11.244378
76                   tea        pancakes  0.004000    0.750000  11.029412
56                  mint             ham  0.004000    0.272727  10.227273
11           blueberries     cooking oil  0.004000    0.500000   9.375000
79                  soda            soup  0.004000    0.750000   9.375000
35  extra dark chocolate          turkey  0.005333    0.666667   8.474576
18        cottage cheese          butter  0.004000    0.214286   8.458647
23  extra dark chocolate         chicken  0.004000    0.500000   8.152174